### ISSUE TITLE
You may want to depend on the offical couchbase lite nodejs bindings

### ISSUE THREAD

**Issue by frank-dspeed** [recouch/couchbase-lite-js#1]
https://github.com/couchbaselabs/vscode-cblite/pull/9

https://github.com/couchbaselabs/vscode-cblite

see the readme for build instructions you can directly use that vscode-cblite package as your dependencie cheers.

**Comment by jpsilva** [comment]
I'll look into it, but I'm hesitant for two reason:

1. Since [vscode-cblite](https://github.com/couchbaselabs/vscode-cblite) doesn't include all features of Couchbase Lite (as some would be pointless in a VS Code plugin), depending on that library would only be a part solution.
2. vscode-cblite is an abstraction on an abstraction (Node.js > C++ > C) and neither the Node.js nor C++ are officially supported. I don't think adding yet another layer of abstraction (especially one with even less support) would make couchbase-lite-js very stable.

**Comment by frank-dspeed** [comment]
@jpsilva this info is outdated listen i create a new couchbaselabs/couchbase-lite-node repo for that i will take your changes into account and when you want you can maintain it with me i only want to do the package structure and automation

as i want it to be dead simple useable and directly package able with other npm solutions for cross platform apps like electron cross platform builds and all that.

i also want to support all Platforms that vscode does support including all Archs.

about your secund point in case of a .node module there is not real abstraction you can if you like that much details inspect the build results as ASSEMBLY the Compiler reduces that what you call a abstraction.

Also we talked internal about that terms like offical and supported

Out of Couchbase view anything not covered by a Enterprise Plan with Support is unsupported but that does not mean that it is not internal used or that you do not get updates or help if you need it.

It is only importent to call them unsupported so that not any customer can say hey i want you to change xy.

**Comment by frank-dspeed** [comment]
@jpsilva https://github.com/couchbase/couchbase-lite-C/pull/318 here is most of the discussion i will open a new issue in here as soon as all is in place.

**Comment by jpsilva** [comment]
After looking into it further, I see that vscode-cblite only supports the enterprise edition of Couchbase Lite. I would like to support that here as well at some point, but I do not want to give up support for the community edition.

Closing this issue as vscode-cblite does not meet the goals of this package.
